@startuml
title Поведенческая UML: временная шкала конкурентного бронирования
robust "Номер" as room
robust "Запрос A" as a
robust "Запрос B" as b
@0
room is Свободен
a is Ожидает
b is Ожидает
@1
a is Блокирует
room is Заблокирован
@2
a is Проверяет
b is Ожидает
@3
a is Создаёт бронь
room is Бронь создана
@4
a is Завершён
b is Блокирует
@5
b is Проверяет
@6
b is Отклонён
@enduml

